In [18]:
import numpy as np
path ='D:\KHDL\khdl\Diem_2a.txt'
diem_2a = np.loadtxt(path,delimiter=',',dtype=np.int8)
print(diem_2a)
print("Kieu du lieu cua phan tu trong mang diem_2a:",diem_2a.dtype)
print("So phan tu cua mang diem_2a:",diem_2a.size)
print("Kich thuoc của mang diem_2a",diem_2a.shape)
print("So chieu cua mang diem_2a:",diem_2a.ndim)
print('Điểm cao nhất của lớp:',diem_2a.max())
print('Điểm thấp nhất của lớp:',diem_2a.min())


[[ 2  4  3  7  5  6  5  6  8  9  3  6  1  9  8  7  3  3  9  5]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7 10  8  5  2  7  7  1]
 [ 1 10  4  9  6  9  0  2  3  1  8  6  8  4  2  9  2  9  5  0]
 [ 6  3  0  8  3  7  7  2  6  8  7  3  4  1  5  9  1  0  2 10]
 [ 4  3  6  7  4  5  2  6  9  4  3  9  9  4  5  7  2 10  9  4]
 [ 2  3  8 10  4  5  9  5  4  7 10  1  8  4  3  9  6  3  6  7]
 [ 9  9  1 10  9  9  5  9  6  3  9  5  1 10  7 10  2  8  8  1]
 [ 8  8  7  8  6  7  7  8  6  7  8  6  7  6  8  8  7  6  8  8]
 [ 6  7  8  9 10  9  2  2  6  1 10  9  6  3  9  5  9  8  1  1]
 [ 7  8  7  8  6 10 10  6  8 10  8  9  8  8  5 10  8  7  8  7]]
Kieu du lieu cua phan tu trong mang diem_2a: int8
So phan tu cua mang diem_2a: 200
Kich thuoc của mang diem_2a (10, 20)
So chieu cua mang diem_2a: 2
Điểm cao nhất của lớp: 10
Điểm thấp nhất của lớp: 0


In [19]:
print('Điểm cao nhất của lớp:',diem_2a.max())
print('Điểm thấp nhất của lớp:',diem_2a.min())


Điểm cao nhất của lớp: 10
Điểm thấp nhất của lớp: 0


In [25]:
print('Tổng tất cả các điểm trong các lớp 2A:',diem_2a.sum())
print('-----------------------------------------------------')
for i in range(0,diem_2a.shape[1]):
    print('Tổng điểm các môn của học sinh',i,':',diem_2a[:,i].sum())
    print('Điểm trung bình các môn của học sinh',i,':',diem_2a[:,i].mean())

Tổng tất cả các điểm trong các lớp 2A: 1184
-----------------------------------------------------
Tổng điểm các môn của học sinh 0 : 48
Điểm trung bình các môn của học sinh 0 : 4.8
Tổng điểm các môn của học sinh 1 : 60
Điểm trung bình các môn của học sinh 1 : 6.0
Tổng điểm các môn của học sinh 2 : 47
Điểm trung bình các môn của học sinh 2 : 4.7
Tổng điểm các môn của học sinh 3 : 86
Điểm trung bình các môn của học sinh 3 : 8.6
Tổng điểm các môn của học sinh 4 : 62
Điểm trung bình các môn của học sinh 4 : 6.2
Tổng điểm các môn của học sinh 5 : 68
Điểm trung bình các môn của học sinh 5 : 6.8
Tổng điểm các môn của học sinh 6 : 56
Điểm trung bình các môn của học sinh 6 : 5.6
Tổng điểm các môn của học sinh 7 : 54
Điểm trung bình các môn của học sinh 7 : 5.4
Tổng điểm các môn của học sinh 8 : 59
Điểm trung bình các môn của học sinh 8 : 5.9
Tổng điểm các môn của học sinh 9 : 51
Điểm trung bình các môn của học sinh 9 : 5.1
Tổng điểm các môn của học sinh 10 : 72
Điểm trung bình các môn của học s